application-settings:
    embeds:
        branding:
            type: one
            entity: application-settings-branding
        posts:
            type: one
            entity: application-settings-posts
        notifications:
            type: one
            entity: application-settings-notifications
        support:
            type: one
            entity: application-settings-support
        privacyPolicy:
            type: one
            entity: application-settings-privacy-policy
