product-frequency:
    attributes:
        freq:
            type: string
            description: 'The frequency pattern: daily, weekly, monthly, yearly, variable'
            defaultValue: variable
        interval:
            type: integer
            defaultValue: 1
