product-email-deployment-optin:
    entity:
        persistence:
            key: mongodb
            db: radix
            schemata:
                - { keys: { email: 1, product: 1 }, options: { unique: true }}
    mixins: [ 'timestampable' ]
    attributes:
        email:
            type: string
        optedIn:
            type: boolean
            defaultValue: false
    relationships:
        product:
            type: one
            entity: product-email-deployment
