imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
as3_modlr:
    persisters:
        default:
            type: mongodb
            parameters:
                host: mongodb://mongo.platform.baseplatform.io:27017?replSet=platform

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://redis.platform.baseplatform.io/8
            options:
                connection_persistent: true
