services:
    app_bundle.command.integration.abstract:
        abstract: true
        arguments: [ "@app_bundle.integration.manager" ]

    app_bundle.command.integration.account_push:
        parent: app_bundle.command.integration.abstract
        class: AppBundle\Command\Integration\AccountPushCommand
        tags:
            - { name: console.command }

    app_bundle.command.integration.question_pull:
        parent: app_bundle.command.integration.abstract
        class: AppBundle\Command\Integration\QuestionPullCommand
        tags:
            - { name: console.command }

    app_bundle.command.integration.identify:
        parent: app_bundle.command.integration.abstract
        class: AppBundle\Command\Integration\IdentifyCommand
        tags:
            - { name: console.command }
