services:
    app_bundle.event_subscriber.core_user:
        private: true
        class: AppBundle\EventSubscriber\CoreUserSubscriber
        arguments: [ "@security.encoder_factory" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.form_field:
        private: true
        class: AppBundle\EventSubscriber\FormFieldSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.model_factories:
        private: true
        class: AppBundle\EventSubscriber\ModelFactorySubscriber
        arguments: [ "@service_container" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.post:
        private: true
        class: AppBundle\EventSubscriber\PostSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.post_stream:
        private: true
        class: AppBundle\EventSubscriber\PostStreamSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.keyable:
        private: true
        class: AppBundle\EventSubscriber\KeyableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.product_website:
        private: true
        class: AppBundle\EventSubscriber\ProductWebsiteSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.timestampable:
        private: true
        class: AppBundle\EventSubscriber\TimestampableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.question:
        private: true
        class: AppBundle\EventSubscriber\QuestionSubscriber
        arguments: [ "@app_bundle.question.type_manager" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.question_choice:
        private: true
        class: AppBundle\EventSubscriber\QuestionChoiceSubscriber
        arguments: [ "@app_bundle.question.type_manager" ]
        tags:
            - { name: as3_modlr.event_subscriber }
