core-application-user:
    entity:
        persistence:
            key: mongodb
            db: radix
            schemata:
                - { keys: { application: 1, user: 1 }, options: { unique: true }}
                - { keys: { user: 1 }}
    mixins: [ 'timestampable' ]
    attributes:
        roles:
            type: array
            defaultValue: [ ROLE_USER ]
    relationships:
        user:
            type: one
            entity: core-user
        application:
            type: one
            entity: core-application
