product-email-deployment:
    entity:
        extends: product
        persistence:
            key: mongodb
            db: radix
    embeds:
        frequency:
            type: one
            entity: product-frequency
