product-tag:
    entity:
        persistence:
            key: mongodb
            db: radix
            schemata:
                - { keys: { key: 1 }, options: { unique: true }}
    mixins: [ 'keyable', 'timestampable' ]
