product:
    entity:
        polymorphic: true
        abstract: true
        persistence:
            key: mongodb
            db: radix
            schemata:
                - { keys: { key: 1 }, options: { unique: true }}
                - { keys: { sequence: 1 } }
                -
                    keys:
                        url: 1
                    options:
                        unique: true
                        partialFilterExpression:
                            _type: "product-website"
                - { keys: { _id: 1, _type: 1 }, options: { unique: true }}
    mixins: [ 'keyable', 'timestampable', 'sequenceable' ]
    attributes:
        description:
            type: string
    relationships:
        tags:
            type: many
            entity: product-tag
