services:
    app_bundle.security.auth.generator_manager:
        class: AppBundle\Security\Auth\AuthGeneratorManager
        calls:
            - [ addGenerator, [ "@app_bundle.security.auth.generator.core_user" ] ]
            - [ addGenerator, [ "@app_bundle.security.auth.generator.account" ] ]

    app_bundle.security.auth.generator.core_user:
        private: true
        class: AppBundle\Security\Auth\CoreUserGenerator
        arguments: [ "@app_bundle.security.jwt.generator_manager", "@request_stack", "@app_bundle.core.account_manager" ]

    app_bundle.security.auth.generator.account:
        private: true
        class: AppBundle\Security\Auth\AccountGenerator
        arguments: [ "@app_bundle.security.jwt.generator_manager" ]

    app_bundle.security.auth.schema:
        class: AppBundle\Security\Auth\AuthSchema

    app_bundle.security.authenticator.api:
        parent: app_bundle.security.authenticator.core_user.abstract
        class: AppBundle\Security\Authenticator\ApiAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.http_utils", "@app_bundle.security.jwt.generator_manager" ]
        calls:
            - [ addRoute, [ "as3_modlr_rest_api" ] ]

    app_bundle.security.authenticator.account:
        private: true
        class: AppBundle\Security\Authenticator\AccountAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.http_utils", "@security.encoder_factory", "@app_bundle.identity.manager", "@app_bundle.security.encoder.legacy_encoder_manager" ]
        calls:
            - [ addRoute, [ "app_bundle_app_auth_submit" ] ]

    app_bundle.security.authenticator.core_user:
        parent: app_bundle.security.authenticator.core_user.abstract
        class: AppBundle\Security\Authenticator\CoreUserAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.http_utils", "@security.encoder_factory", "@app_bundle.security.auth.generator_manager" ]
        calls:
            - [ addRoute, [ "app_bundle_auth_user_submit" ] ]

    app_bundle.security.authenticator.core_user.abstract:
        private: true
        abstract: true

    app_bundle.security.encoder.legacy_encoder_manager:
        private: true
        class: AppBundle\Security\Encoder\LegacyEncoderManager
        calls:
            - [ addEncoder, [ "@app_bundle.security.encoder.legacy.merrick" ] ]

    app_bundle.security.encoder.legacy.merrick:
        private: true
        class: AppBundle\Security\Encoder\MerrickPasswordEncoder

    app_bundle.security.jwt.generator_manager:
        private: true
        class: AppBundle\Security\JWT\JWTGeneratorManager
        calls:
            - [ addGenerator, [ "@app_bundle.security.jwt.generator.core_user" ] ]
            - [ addGenerator, [ "@app_bundle.security.jwt.generator.account" ] ]

    app_bundle.security.jwt.generator.account:
        private: true
        class: AppBundle\Security\JWT\AccountGenerator
        arguments: [ "%secret%" ]

    app_bundle.security.jwt.generator.core_user:
        private: true
        class: AppBundle\Security\JWT\CoreUserGenerator
        arguments: [ "%secret%" ]

    app_bundle.security.login_listener:
        private: true
        class: AppBundle\Security\LoginListener
        arguments: [ "@security.authorization_checker", "@as3_modlr.store" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    app_bundle_security.logout_success_handler:
        private: true
        class: AppBundle\Security\LogoutSuccessHandler
        arguments: [ "@app_bundle.security.auth.generator_manager" ]

    app_bundle_security.logout_success_handler.application:
        private: true
        class: AppBundle\Security\ApplicationLogoutSuccessHandler
        arguments: [ "@app_bundle.identity.manager" ]

    app_bundle.security.user_provider.core_user:
        private: true
        class: AppBundle\Security\User\CoreUserProvider
        arguments: [ "@as3_modlr.store", "@request_stack" ]

    app_bundle.security.user_provider.account:
        class: AppBundle\Security\User\AccountProvider
        arguments: [ "@as3_modlr.store" ]
