services:
    app_bundle.submission.manager:
        class: AppBundle\Submission\SubmissionManager
        arguments: [ "@app_bundle.factory.input_submission", "@app_bundle.identity.manager", "@app_bundle.notifications.manager" ]
        calls:
            - [ addHandler,  [ "@app_bundle.submission.handler.identity_account" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.identity_account.password_reset" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.identity_account.password_reset_generate" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.identity_account.verify_submit" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.identity_account.verify_generate" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.email_opt_in" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.gated_download" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.inquiry" ] ]

    app_bundle.submission.handler.identity_account:
        class: AppBundle\Submission\Handlers\IdentityAccountHandler
        arguments: [ "@app_bundle.factory.identity.account" ]

    app_bundle.submission.handler.identity_account.password_reset:
        class: AppBundle\Submission\Handlers\AccountResetPasswordHandler
        arguments: [ "@app_bundle.identity.password_reset.token_generator", "@app_bundle.identity.manager" ]

    app_bundle.submission.handler.identity_account.password_reset_generate:
        class: AppBundle\Submission\Handlers\AccountResetPasswordGenerateHandler
        arguments: [ "@app_bundle.factory.identity.account", "@app_bundle.security.user_provider.account", "@app_bundle.identity.password_reset.token_generator" ]

    app_bundle.submission.handler.identity_account.verify_generate:
        class: AppBundle\Submission\Handlers\AccountEmailVerifyGenerateHandler
        arguments: [ "@app_bundle.factory.identity.account_email" ]

    app_bundle.submission.handler.identity_account.verify_submit:
        class: AppBundle\Submission\Handlers\AccountEmailVerifySubmitHandler
        arguments: [ "@app_bundle.identity.email_verify.token_generator", "@app_bundle.identity.manager" ]

    app_bundle.submission.handler.email_opt_in:
        class: AppBundle\Submission\Handlers\EmailOptInHandler
        arguments: [ "@app_bundle.factory.product.email_deployment_optin" ]

    app_bundle.submission.handler.gated_download:
        class: AppBundle\Submission\Handlers\GatedDownloadHandler

    app_bundle.submission.handler.inquiry:
        class: AppBundle\Submission\Handlers\InquiryHandler
